#!/bin/sh
update-cheese

DB_URL="http://"$IP":$DB_PORT"
API_URL="https://"$IP":$API_PORT"
UI_URL="http://"$IP":$UI_PORT"

docker rm -f api ui db cheese_docs
echo "Running cheese database server..."
sudo docker run -d -v /data:/data -u root --env PORT=$DB_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --name db -p $DB_PORT:$DB_PORT --rm $DB_IMAGE

sudo python3 $ASSETS_FOLDER"/check_database_server.py" --ip $IP --db_port $DB_PORT

echo "Running cheese UI .."
sudo docker run -d -u root --env CHEESE_API=$API_URL  --name ui -p $UI_PORT:3000 --rm $UI_IMAGE

echo "Running cheese API..."
sudo docker run -d -v /data:/data -it -u root --env API_URL=$DB_URL --env UI_URL=$UI_URL --env PORT=$API_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --name api -p $API_PORT:$API_PORT --rm $API_IMAGE


echo "Running cheese DOCS..."
sudo docker run -d --name cheese_docs -p 9010:9010 --rm $DOCS_IMAGE

API_FOR_DOCS="!!swagger-http https://"$IP":"$API_PORT"/openapi.json!!"

rm -f index.md
echo $API_FOR_DOCS > index.md
sudo docker cp index.md cheese_docs:/opt/themama.ai/docs
