#!/bin/bash
ALL_ARGS=$@

command=$1

while [ $# -gt 0 ]; do
    if [[ $1 == "--"* ]]; then
        v="${1/--/}"
        declare "$v"="$2"
        shift
    fi
    shift
done

for x in $ALL_ARGS
do 
help=$x;
if [ "$x" = "--validate_smiles" ]; then
    validate_smiles="true" ; 
fi

if [ "$x" = "--canonicalize_smiles" ]; then
    canonicalize_smiles="true" ; 
fi

done



if [ "$command" = "start-app" ]; then
    cheese-app
elif [ "$command" = "inference" ]; then
    if [ "$help" = "--help" ]; then
        sudo docker run -it --entrypoint "python" -v /data:/data -u root --env PORT=$DB_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app()' $ALL_ARGS
    else
        cheese-inference --input_file $input_file --gpu_device $gpu_device --validate_smiles $validate_smiles --canonicalize_smiles $canonicalize_smiles
    fi

elif [ "$command" = "embeddings-gpu" ]; then
    if [ "$help" = "--help" ]; then
        sudo docker run -it --entrypoint "python" -v /data:/data -u root --env PORT=$DB_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app()' $ALL_ARGS
    else
    cheese-embeddings --input_file $input_file --dest $dest --gpu_device $gpu_device;
    # echo "Embeddings computation complete ! You can find the results here : /data/"$dest;
    fi
else
    sudo docker run -it --entrypoint "python" -v /data:/data -u root --env PORT=$DB_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app()' $ALL_ARGS
fi
