#!/bin/bash
while [ $# -gt 0 ]; do
    if [[ $1 == "--"* ]]; then
        v="${1/--/}"
        declare "$v"="$2"
        shift
    fi
    shift
done


EXTENSION=".csv"
DELIMITER=","

DEVICE="cuda"
BATCH_SIZE=1024

MAXSIZE=2000000

INPUT_FILE=$SOURCE_DIR"/"$input_file
DEST_INPUT_FILE=$DEST_DIR"/"$input_file

# Get file size
echo Getting file size of $INPUT_FILE
FILESIZE=$(du $INPUT_FILE | awk '{print $1}')
# Checkpoint
echo "Size of $INPUT_FILE = $FILESIZE KB."

if [ "$index_type" = "auto" ] ||  [ "$index_type" = "" ]; then

    if (( FILESIZE > MAXSIZE)); then
        INDEX_TYPE="clustered"
    else
        INDEX_TYPE="in_memory"
    fi

else
INDEX_TYPE=$index_type

fi



CHUNK_SIZE=100000  # Chunk size for embeddings computation

echo "Running CHEESE inference..."
echo "Saving outputs to $dest"
echo "Making output directory $dest"
mkdir $dest
sudo docker run -v $SOURCE_DIR:$DEST_DIR -it --env CHEESE_LICENSE_FILE=$LICENSE_FILE --env LICENSING=$LICENSING --gpus all --rm $INFERENCE_IMAGE --index_type $INDEX_TYPE --input_file $DEST_INPUT_FILE --extension $EXTENSION --delimiter $DELIMITER --output_directory $dest --gpu_device_ids $gpu_devices --batch_size $BATCH_SIZE --chunk_size $CHUNK_SIZE --validate_smiles $valid_smiles --canonicalize_smiles $canonical_smiles
