#!/bin/bash
ALL_ARGS=$@

command=$1


VALIDATE_SMILES="false"
CANONICALIZE_SMILES="false"

for x in $ALL_ARGS
do 
HELP=$x;

if [ "$x" = "--validate_smiles" ]; then
    VALIDATE_SMILES="true" ; 
fi

if [ "$x" = "--canonicalize_smiles" ]; then
    CANONICALIZE_SMILES="true" ; 
fi

done

while [ $# -gt 0 ]; do
    if [[ $1 == "--"* ]]; then
        v="${1/--/}"
        declare "$v"="$2"
        shift
    fi
    shift
done



if [ "$command" = "start-app" ]; then
    cheese-app
elif [ "$command" = "inference" ]; then
    if [ "$HELP" = "--help" ]; then
        sudo docker run -it --entrypoint "python" -v /data:/data -u root --env PORT=$DB_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
    else
        cheese-inference --input_file $input_file --gpu_device $gpu_device --valid_smiles $VALIDATE_SMILES --canonical_smiles $CANONICALIZE_SMILES --index_type $index_type
    fi

elif [ "$command" = "embeddings-gpu" ]; then
    if [ "$HELP" = "--help" ]; then
        sudo docker run -it --entrypoint "python" -v /data:/data -u root --env PORT=$DB_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
    else
        cheese-embeddings --input_file $input_file --dest $dest --gpu_device $gpu_device;
    fi
else
    sudo docker run -it --entrypoint "python" -v /data:/data -u root --env PORT=$DB_PORT --env CONFIG_FILE=$CONFIG_FILE --env LICENSING=$LICENSING --env CHEESE_LICENSE_FILE=$LICENSE_FILE --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
fi
