#!/bin/bash
while [ $# -gt 0 ]; do
    if [[ $1 == "--"* ]]; then
        v="${1/--/}"
        declare "$v"="$2"
        shift
    fi
    shift
done


EXTENSION=".csv"
DELIMITER=","

DEVICE="cuda"
BATCH_SIZE=1024


INPUT_FILE=$input_file

INDEX_TYPE="in_memory"


# Specify save format
if [ "$save_format" = "" ]; then
    SAVE_FORMAT="numpy"
else
    SAVE_FORMAT=$save_format

fi

CHUNK_SIZE=100000  # Chunk size for embeddings computation

echo "Running CHEESE embeddings computation..."
OUTPUT_DIRECTORY=$DEST_DIR"/"$dest
NEW_OUTPUT_DIRECTORY=$SOURCE_DIR"/"$dest
echo Saving outputs to $NEW_OUTPUT_DIRECTORY
mkdir $NEW_OUTPUT_DIRECTORY
sudo docker run -v $SOURCE_DIR:$DEST_DIR -it --env CHEESE_LICENSE_FILE=$LICENSE_FILE --env LICENSING=$LICENSING --gpus all --rm $INFERENCE_IMAGE --index_type $INDEX_TYPE --input_file $INPUT_FILE --extension $EXTENSION --delimiter $DELIMITER --output_directory $OUTPUT_DIRECTORY --gpu_device_ids $gpu_devices --batch_size $BATCH_SIZE --chunk_size $CHUNK_SIZE --process_file "true" --embeddings_computation "true" --make_indexes "false" --balance_clusters "false" --save_format $SAVE_FORMAT
sudo mv $NEW_OUTPUT_DIRECTORY $NEW_OUTPUT_DIRECTORY"_new"
sudo mv $NEW_OUTPUT_DIRECTORY"_new/embeddings" $NEW_OUTPUT_DIRECTORY
sudo rm -rf $NEW_OUTPUT_DIRECTORY"_new"