#!/bin/sh
# Login to Azure CR
echo "Pulling from repo"
cd $ASSETS_FOLDER
cd ..
git pull

sudo cp $ASSETS_FOLDER/cheese /usr/local/bin
sudo chmod +x /usr/local/bin/cheese

sudo cp $ASSETS_FOLDER/cheese-inference /usr/local/bin
sudo chmod +x /usr/local/bin/cheese-inference

sudo cp $ASSETS_FOLDER/cheese-embeddings /usr/local/bin
sudo chmod +x /usr/local/bin/cheese-embeddings

sudo cp $ASSETS_FOLDER/cheese-app /usr/local/bin
sudo chmod +x /usr/local/bin/cheese-app

echo updating CHEESE...
sudo docker login -u cheese-customer-test -p $CHEESE_PASSWORD $REPO_NAME

# # Pull the CHEESE app images
sudo docker system prune -f
sudo docker pull $UI_IMAGE
sudo docker pull $DB_IMAGE
sudo docker pull $API_IMAGE
sudo docker pull $DOCS_IMAGE
sudo docker pull $INFERENCE_IMAGE

