#!/bin/bash -e

ALL_ARGS=$@

command=$1

if [ "$command" = "test" ]; then
    test_component=$2
fi


VALIDATE_SMILES="false"
CANONICALIZE_SMILES="false"

for x in $ALL_ARGS
do 
HELP=$x;

if [ "$x" = "--validate_smiles" ]; then
    VALIDATE_SMILES="true" ; 
fi

if [ "$x" = "--canonicalize_smiles" ]; then
    CANONICALIZE_SMILES="true" ; 
fi

done

while [ $# -gt 0 ]; do
    if [[ $1 == "--"* ]]; then
        v="${1/--/}"
        declare "$v"="$2"
        shift
    fi
    shift
done


if [ "$dest" = "" ]; then
    INFERENCE_OUTPUT_DIR="output"
else
    INFERENCE_OUTPUT_DIR=$dest

fi

# Specify GPU device
if [ "$gpu_devices" = "" ]; then
    GPU_DEVICES="0"

else
    GPU_DEVICES=$gpu_devices
fi

# Specify Search type for cheese-embeddings
if [ "$search_types" = "" ]; then
    SEARCH_TYPES="all"
else
    SEARCH_TYPES=$search_types
fi

# Specify chunk size for inference
if [ "$chunk_size" = "" ]; then
    CHUNK_SIZE=100000
else
    CHUNK_SIZE=$chunk_size
fi

# Specify embeddings computation batch size for inference
if [ "$batch_size" = "" ]; then
    BATCH_SIZE=1024
else
    BATCH_SIZE=$batch_size
fi

# Specify clustering batch size for inference
if [ "$clustering_batch_size" = "" ]; then
    CLUSTERING_BS=10000
else
    CLUSTERING_BS=$clustering_batch_size
fi



if [ "$command" = "update_config" ]; then
    mkdir $HOME/.config
    mkdir $HOME/.config/cheese
    cat $env_config >> ~/.config/cheese/cheese-env-user.conf

else
    source /etc/cheese/cheese-env.sh $ENV_CONFIG
    

    if [ "$command" = "start_app" ]; then
        cheese-app

    elif [ "$command" = "update" ]; then
        update-cheese

    elif [ "$command" = "inference" ]; then
        if [ "$HELP" = "--help" ]; then
            docker run -u $UID  --entrypoint "python" -v /:/data --env PORT=$DB_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env TRANSFORMERS_CACHE=/tmp --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
        else
            cheese-inference --input_file $input_file --dest $INFERENCE_OUTPUT_DIR --gpu_devices $GPU_DEVICES --valid_smiles $VALIDATE_SMILES --canonical_smiles $CANONICALIZE_SMILES --clustering_bs $CLUSTERING_BS --chunk_size $CHUNK_SIZE --batch_size $BATCH_SIZE --index_type $index_type
        fi

    elif [ "$command" = "embeddings_gpu" ]; then
        if [ "$HELP" = "--help" ]; then
            docker run -u $UID  --entrypoint "python" -v /:/data --env PORT=$DB_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --env TRANSFORMERS_CACHE=/tmp --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
        else
            cheese-embeddings --input_file $input_file --dest $INFERENCE_OUTPUT_DIR --search_types $SEARCH_TYPES --gpu_devices $GPU_DEVICES --save_format $save_format;
        fi
    


    elif [ "$command" = "test" ]; then
        # sudo rm -rf /tmp/cheese_test
        mkdir /tmp/cheese_test && exit 0
        sudo chmod -R 777 /tmp/cheese_test 

        if [ "$test_component" = "cli" ]; then

            # Start CHEESE CLI and generate test script
            docker run -u root --entrypoint "python" -v /:/data --env PORT=$DB_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --env TRANSFORMERS_CACHE=/tmp --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' test cli
            bash /tmp/cheese_test/test_cheese_cli.sh

        elif [ "$test_component" = "api" ]; then

        echo "Starting app for testing"
        cheese-app test

        # Define Endpoints
        DB_URL="http://"$IP":$DB_PORT"
        API_URL="http://"$IP":$API_PORT"
        UI_URL="http://"$IP":$UI_PORT"


        echo "Removing existing API container"
        docker rm -f api

        echo "Testing API"
        API_CONTAINER="${USER}_api_test"
        docker run -u root -v /:/data --env API_URL=$DB_URL --env UI_URL=$UI_URL --env PORT=$API_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --name $API_CONTAINER --entrypoint bash -p $API_PORT:$API_PORT --rm $API_IMAGE -c "cd tests; pytest"


        else
            echo "Error ! Please specify the component you want to test : 'cli' or 'api'."
            exit 1  
        fi

    else
    # Run other commands in CHEESE CLI
    docker run -u $UID --entrypoint "python" -v /:/data --env PORT=$DB_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --env TRANSFORMERS_CACHE=/tmp --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS

    fi
fi