#!/bin/bash
# Login to Azure CR

while [ $# -gt 0 ]; do
    if [[ $1 == --* ]]; then
        v=${1/--/}
        declare $v=$2
        shift
    fi
    shift
done

if [ ! $install = "True" ]; then
# Pull from repo only in usage mode
echo "Pulling from repo"
cd $ASSETS_FOLDER
git pull

fi


source /etc/cheese/cheese-env.sh

sudo cp $ASSETS_FOLDER/scripts/cheese /usr/local/bin
sudo chmod +x /usr/local/bin/cheese

sudo cp $ASSETS_FOLDER/scripts/cheese-inference /usr/local/bin
sudo chmod +x /usr/local/bin/cheese-inference

sudo cp $ASSETS_FOLDER/scripts/cheese-embeddings /usr/local/bin
sudo chmod +x /usr/local/bin/cheese-embeddings

sudo cp $ASSETS_FOLDER/scripts/cheese-app /usr/local/bin
sudo chmod +x /usr/local/bin/cheese-app

echo updating CHEESE...
sudo docker login -u cheese-customer-test -p $CHEESE_PASSWORD $REPO_NAME

# # Pull the CHEESE app images
sudo docker system prune -f
sudo docker pull $UI_IMAGE
sudo docker pull $DB_IMAGE
sudo docker pull $API_IMAGE
sudo docker pull $DOCS_IMAGE
sudo docker pull $INFERENCE_IMAGE

